all: Course

Course:  Main.cpp Item.cpp Enemy.cpp Player.cpp Orc.cpp Goblin.cpp Potion.cpp Grenade.cpp GameWorld.cpp CombatUnit.cpp
	g++ Main.cpp Item.cpp Enemy.cpp Player.cpp Orc.cpp Goblin.cpp Potion.cpp Grenade.cpp GameWorld.cpp CombatUnit.cpp -std=c++11 -o Lab3StarterCode
